// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdn9cRnh1_4PgN16KDaC9AjsKmVS-6--g',
    appId: '1:1074553653742:web:28658709847eace3a526ff',
    messagingSenderId: '1074553653742',
    projectId: 'triva-7138e',
    authDomain: 'triva-7138e.firebaseapp.com',
    storageBucket: 'triva-7138e.firebasestorage.app',
    measurementId: 'G-BTKXQVJ243',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPjIxg5cV5wVQUX1Svdb4jrKusCFl3-no',
    appId: '1:1074553653742:android:a577626fe1b33fcda526ff',
    messagingSenderId: '1074553653742',
    projectId: 'triva-7138e',
    storageBucket: 'triva-7138e.firebasestorage.app',
  );
}
