import 'package:firebase_core/firebase_core.dart';

/// Service wrapper for Firebase Core initialization.
///
/// The TRIVA app must call [init] with its [FirebaseOptions] generated by the
/// FlutterFire CLI before using Firebase services.
class FirebaseService {
  /// Initializes Firebase with the given [options].
  ///
  /// Must be called once in `bootstrap()` before `runApp()`.
  static Future<void> init({
    required FirebaseOptions options,
  }) async {
    await Firebase.initializeApp(options: options);
  }
}
